---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - docker-compose
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker
        
    - name: Add "ubuntu" user to "docker" group
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      
    - name: Register uname -s
      shell: uname -s
      ignore_errors: yes
      register: uname_s_result
      
    - name: Register uname -m
      shell: uname -m
      ignore_errors: yes
      register: uname_m_result
    
    - debug: msg="{{ uname_s_result.stdout }}"
    - debug: msg="{{ uname_m_result.stdout }}"
    
    - name: Install docker-compose 2.14.0 from official github repo
      get_url:
        url : "https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-{{ uname_s_result.stdout }}-{{ uname_m_result.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: '+x'
    
  
    
    
    
    
    
    
    
    
    
    