---
# tasks file for deploy_demo_docker
- name: Prints Hello World
  ansible.builtin.debug:
    msg:
    - "running tasks file for deploy_demo_docker..."
    
- name: Make compose-demo directory
  ansible.builtin.file:
    path: /home/ubuntu/compose-demo
    owner: ubuntu
    group: docker
    state: directory
    mode: '0755'
    
- name: Make an app directory inside compose-demo directory
  ansible.builtin.file:
    path: /home/ubuntu/compose-demo/app
    owner: ubuntu
    group: docker
    state: directory
    mode: '0755'

- name: Add index.html
  template: 
    src: ../files/index.html 
    dest: /home/ubuntu/compose-demo/app/index.html
    owner: ubuntu
    group: docker
  
- name: Add docker-compose.yml
  template: 
    src: ../files/docker-compose.yml 
    dest: /home/ubuntu/compose-demo/docker-compose.yml
    owner: ubuntu
    group: docker

- name: Get running containers
  docker_host_info:
    containers: yes
  register: docker_info

- name: Stop running containers
  docker_container:
    name: "{{ item }}"
    state: stopped
  loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
  
- name: Run "docker-compose up"
  become: false
  community.docker.docker_compose:
    project_src: /home/ubuntu/compose-demo
    project_name: compose-demo
  register: output